trigger:
  - main

variables:
  dockerRegistryServiceConnection: 'acr-connection'
  imageRepository: 'codealpha-azure-app'
  containerRegistry: 'sujoycodealphaacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  appName: 'sujoy-codealpha-cicd'

stages:
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - job: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: Build and push image to ACR
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest

  - stage: Deploy
    displayName: Deploy to Azure App Service
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: Deploy
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy container to App Service
            inputs:
              azureSubscription: 'azure-rm-connection'
              appName: $(appName)
              containers: '$(containerRegistry)/$(imageRepository):$(tag)'